### ISSUE TITLE
录制Surface  可以用在GLSurfaceView 上吗？

### ISSUE THREAD

**Issue by ithour** [yellowcath/SVideoRecorder#1]

**Comment by yellowcath** [comment]
可以的，在我们实际项目里用的就是GLSurfaceView

**Comment by ithour** [comment]
嗯嗯，好的，谢谢。我还想请教下。录制gif要怎么做呢。有个方案就是 录制MP4  再用ffmpeg 转gif。但我感觉有些大材小用了。而且，ffmpeg 几十精简版的也有好几M，是否有其他更灵活的方案呢。gif上还需要文字水印等等的需求。

**Comment by yellowcath** [comment]
这个我没做过，搜了一下。有个直接合成gif的库，好像只有几十k
http://jiggawatt.org/badc0de/android/index.html#gifflen
这个是直接把图片合成gif。我理了下大体步骤
录制数据帧->Bitmap->加水印文字->合成gif

**Comment by yellowcath** [comment]
对了，如果加水印之类的需求多的话可以步骤可以改一下
加水印文字->录制数据帧->Bitmap->合成gif,用opengl来加性能会更高一些

**Comment by ithour** [comment]
嗯嗯，好的谢谢
